name: Upload File to S3

on:
  schedule:
    - cron: "0 4 * * *"  # Runs every day at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering
  
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Fetch basis data
        run: python fetch_basis_data.py

      - name: Fetch price data
        run: python fetch_price_data.py

      - name: Upload File to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: python upload_to_s3.py
